module.exports = {
	host: '',
	port: 5000,
	secret: 'this is a testing secret',
	msg_buf_size: 50,
	item_pic_size: 9,
	encrypt_algo: 'aes-256-ctr',
	db_domain: '',
	db_u: '',
	db_p: '',
	db_db: '',
	db_port: '',
	email_a: '',
	email_p: '',
};
