module.exports = {
	host: '',
	port: 5000,
	secret: 'this is a testing secret',
	msg_buf_size: 50,
	item_pic_size: 9,
	db_domain: 'localhost',
	encrypt_algo: 'aes-256-ctr',
	db_u: '',
	db_p: '',
	db_db: 'test',
	db_port: '27017',
	email_a: '',
	email_p: '',
};
