module.exports = {
	host: '',
	port: 5000,
	secret: 'this is a testing secret',
	msg_buf_size: 50,
	item_pic_size: 9,
	recommend_size: 10,
	encrypt_algo: 'aes-256-ctr',
	db_domain: 'cu-hk.me',
	db_u: 'buybuy',
	db_p: 'buybuy321',
	db_db: 'buybuy',
	db_port: '27017',
	email_a: '',
	email_p: '',
};
